barra = '='  *40
print(barra)
nome = input('Digite seu nome: ')
print(barra)
print('Seu nome é: ')
print(barra)
print(nome.upper())
print(barra)
print(nome.lower())
print(barra)
print('Ele tem {} caracteres sem os espaços'.format(len(nome.replace(" ",""))))
print(barra)
nome = nome.split()
print('O primeiro nome tem {} caracteres'.format(len(nome[0])))